services:
  backend:
    build:
      context: ./devops_backend
    ports:
      - "5001:5001"

  frontend:
    build:
      context: ./devops_frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_HOST: "ec2-13-51-198-31.eu-north-1.compute.amazonaws.com"
    depends_on:
      - backend