services:
  backend:
    build:
      context: ./devops_backend
    ports:
      - "5001:5001"
    environment:
      MINITWIT_DB_URL: jdbc:postgresql://db:5432/minitwit
      MINITWIT_DB_USER: minitwit_user
      MINITWIT_DB_PASSWORD: minitwit_password
    depends_on:
      - db

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: minitwit
      POSTGRES_USER: minitwit_user
      POSTGRES_PASSWORD: minitwit_password
    volumes:
      - db_data_ci:/var/lib/postgresql/data

volumes:
  db_data_ci:
