services:
  backend:
    build:
      context: ./devops_backend
    ports:
      - "5001:5001"
    volumes:
      - minitwit_db:/data
    environment:
      MINITWIT_DB_PATH: /data/minitwit.db

  frontend:
    build:
      context: ./devops_frontend
      args:
        NEXT_PUBLIC_API_HOST: "http://ec2-13-51-198-31.eu-north-1.compute.amazonaws.com"
        NEXT_PUBLIC_API_PORT: "5001"
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_HOST: "http://ec2-13-51-198-31.eu-north-1.compute.amazonaws.com"
      NEXT_PUBLIC_API_PORT: "5001"
    depends_on:
      - backend
volumes:
  minitwit_db:
