{
 "title": "MiniTwit - Logs dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Backend logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=~\".*backend.*\"}"
    }
   ]
  },
  {
   "title": "Backend Warnings",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=~\".*backend.*\"} |= \"WARN\""
    }
   ]
  },
  {
   "title": "Backend errors",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=~\".*backend.*\"} |= \"ERROR\""
    }
   ]
  },
  {
   "title": "Follow Unfollow logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=~\".*backend.*\"} |= \"follow\""
    }
   ]
  },
  {
   "title": "Message post count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service=~\".*backend.*\"} |= \"message posted\" [5m]))"
    }
   ]
  },
  {
   "title": "Msg flow",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=~\".*backend.*\"} |~ \"post message|message posted\""
    }
   ]
  },
  {
   "title": "Warning count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service=~\".*backend.*\"} |= \"WARN\" [5m]))"
    }
   ]
  },
  {
   "title": "Error count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service=~\".*backend.*\"} |~ \"Bad request|Forbidden|Exception|error_msg|User not found\" [5m]))"
    }
   ]
  },
  {
   "title": "Register flow",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=~\".*backend.*\"} |~ \"POST /register|registered username|Register failed\""
    }
   ]
  }
 ]
}