apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops_backend.fullname" . }}
  labels:
    {{- include "devops_backend.labels" . | nindent 4 }}
spec:
   ports:
     - name: http
       port: 30552
       targetPort: 30552
       
   selector: 
      matchLabels:
      app: devops-backend
    
