spring.application.name=itu_minitwit
server.port=5001

spring.datasource.url=${MINITWIT_DB_URL:jdbc:postgresql://ec2-13-51-198-31.eu-north-1.compute.amazonaws.com:5432/minitwit}
spring.datasource.username=${MINITWIT_DB_USER:postgres}
spring.datasource.password=${MINITWIT_DB_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=never