spring.application.name=itu_minitwit
server.port=5001

# Expose prometheus metrics endpoint
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=always