spring.application.name=itu_minitwit
server.port=5001

spring.datasource.url=${MINITWIT_DB_URL:jdbc:postgresql://ec2-13-60-32-149.eu-north-1.compute.amazonaws.com:5432/minitwit}
spring.datasource.username=${MINITWIT_DB_USER:postgres}
spring.datasource.password=${MINITWIT_DB_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=never

# Expose prometheus metrics endpoint
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=always

logging.level.root=INFO
logging.level.com.yourapp=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] [%logger{36}] %msg%n