name: build_and_deploy_devops_backend
 
on:
  push:
    branches: [ anders/kubernetes ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
   branches: [ anders/kubernetes   ]

env:
  HOST: ec2-16-171-175-255.eu-north-1.compute.amazonaws.com 
  USER: ubuntu

jobs:
  deploy:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:

    - name: Checkout repository
        uses: actions/checkout@v4

    - name: 'Install helm chart'
      uses: 'deliverybot/helm@v1'
      with:
        release: 'devops-backend-0.1.0'
        namespace: 'default'
        chart: './helm/devops-backend'
        values: |
          name: devops-backend

    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ env.HOST }}
        username: ${{ env.USER }}
        key: ${{ secrets.VAGRANT }}
        port: ${{ secrets.PORT }}
        source: "devops-backend-0.1.0.tgz"
        target: "/home/ubuntu"

      - name: File commands
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USER }}
          key: ${{ secrets.VAGRANT }}
          port: 22
          script: |
            helm uninstall devops-backend
            docker login -u andersfrimann -p itudevops
            tar -xzvf /home/ubuntu/devops-frontend-0.1.0.tgz
            helm install devops-frontend ./devops-backend
            kubectl get pods
            kubectl get services
            kubectl get deployments
            export DEVOPS_BACKEND_PORT="$(kubectl get services/devops-backend -o go-template='{{(index .spec.ports 0).nodePort}}')"
            echo "NODE_PORT=$NODE_PORT"